### ISSUE TITLE
导出pdf时有问题

### ISSUE THREAD

**Issue by yan-yb** [HappySimple/Typora-theme-Happysimple#13]
导出的pdf文件右侧多了个滚动条

**Comment by yan-yb** [comment]
额是我自己图片比例偏大了

**Comment by Anonym0usPlayer** [comment]
把happysimple-set.css里面的
html {
font-size: 11px !important;
}
这段注释或者删掉就暂时解决了。

**Comment by zleo-ai** [comment]
```css
/* --------------------------------------- PDF配置 --------------------------------------- */
@media print {
  @page {
    margin: 2mm 0mm;
  }
  html {
    font-size: 11px !important;
  }
  img {
    border: var(--img-border) !important;
    border-radius: var(--img-border-radius) !important;
  }
  /* 隐藏滚动条 */
  ::-webkit-scrollbar {
    display: none;
  }
}
```
