### ISSUE TITLE
MacOS下图片无法正常显示 解决方案

### ISSUE THREAD

**Issue by Wangmz-1211** [HappySimple/Typora-theme-Happysimple#22]
**问题描述**
图片只显示border
![image-20231009165824720]( http://wangmz-markdown.oss-cn-shanghai.aliyuncs.com/img/image-20231009165824720.png )
**解决方案**
注释掉以下两行
./happysimple/source/happysimple-set.css
```css
.md-image img {
    margin: var(--img-margin);
    padding: var(--img-padding);
    text-align: center;
    border: var(--img-border);
    border-radius: var(--img-border-radius);
    /*content: var(--img-name); */   
}
```
./happysimple.css
```css
    /* 图片 */
    --img-margin: 20px 0px;
    --img-padding: 0px;
    --img-border: 2px solid #000;
    --img-border-radius: 5px;
    /* --img-name: '';                                 若想自动编号,用"Fig." counter(imgNum);替代 */
    --img-font-family: 'Times New Roman';
    --img-font-size: 1.0rem;
```
