### ISSUE TITLE
在目录[toc]中四级标题无法在三级标题之后展示

### ISSUE THREAD

**Issue by ItRicardo** [HappySimple/Typora-theme-Happysimple#40]
![image](https://github.com/user-attachments/assets/72846016-9255-48aa-833e-2775c79ab788)
![image](https://github.com/user-attachments/assets/1cc6fb67-e0d5-4ec7-a0f6-fa41a6ab0ffe)

**Comment by ItRicardo** [comment]
# 已解决
## 说明
解决方案，前往配置文件中添加上h4 h5 h6的目录部分的缩进即可

## 【步骤】
1. 打开文件`...\Typora\themes\happysimple\source\happysimple-set.css` 
2. 在第130行插入如下代码
```css
.md-toc-h4 .md-toc-inner{
    text-indent: 6em;
}
.md-toc-h5 .md-toc-inner{
    text-indent: 8em;
}
.md-toc-h6 .md-toc-inner{
    text-indent: 10em;
}
```
3. 代码添加后
> 不知道为什么截图无法上传了，直接看结果吧


## 【预览】
![image](https://github.com/user-attachments/assets/45567878-6d6d-479f-8cce-fd9a966cd0f0)
